### ISSUE TITLE
Compiler.py requires htmlc to be installed

### ISSUE THREAD

**Issue by timostrating** [HTML-as-programming-language/HTML-as-programming-language#23]
from htmlc import utils
from htmlc.c_linker import CLinker
from htmlc.gcc.avr import AVR
from htmlc.gcc.gcc import GCC
from htmlc.html_parser import HTMLParser
from htmlc.diagnostics import diagnose, contains_error
from htmlc.lexer import Lexer
from htmlc.linker import Linker
from htmlc.mapped_c_string import MappedCString

## Expected Behavior
python3 compiler.py  should be callable

## Actual Behavior
Traceback (most recent call last):
  File "compiler.py", line 7, in <module>
    from htmlc import utils
ModuleNotFoundError: No module named 'htmlc'

## Steps to Reproduce the Problem

  1. $ python3 compiler.py

## Specifications

  - Version: none installed
  - Platform: Linux

**Comment by hilkojj** [comment]
`python3 compiler.py` will indeed not work.

Try the following:

- Go to 'HTML_to_C_compiler' (that is the directory with the `__main__.py` file)
- Then do `python3 . htmlc`
